### ISSUE TITLE
Further Idears

### ISSUE THREAD

**Issue by ellerbrock** [nccgroup/gitpwnd#1]
Hi Eduard,

a college just send me the link to your article [Hackers Can Use Git Repos for Stealthy Attack on Developers](http://www.securityweek.com/hackers-can-use-git-repos-stealthy-attack-developers).

Just for an idea of further evil thinking could be the setup of an CI System like [Travis](https://travis-ci.org/) to execute commands. You can find a few Travis examples in my repos:

- Docker: https://github.com/ellerbrock/travis-link-checker
- Node.js: https://github.com/ellerbrock/travis-vulnerability-scanner
- Ruby: https://github.com/ellerbrock/travis-deadlink-scanner

Cheers Maik

**Comment by clintgibler** [comment]
Hey @ellerbrock! 

Thanks for reaching out and sorry for the response delay. Those are interesting examples of useful scripts you can tie into the CI process. As the primary purpose of GitPwnd is to be used by penetration testers or internal security engineers who are attempting to attack a development environment, I don't think checking for broken links or vulnerable dependencies would be useful to an attacker in this scenario, though I could see them being useful to many other people.

We have thought about including payloads targeting specific CI infrastructure, like Travis or Jenkins, but have not implemented them yet.

In summary, thanks for reaching out and sharing the links, it's much appreciated. While I think the tools you shared are useful in many contexts, I don't think they're a good fit to integrate into GitPwnd because of their differing purposes.

I'm going to close this issue as I don't plan to take any action on it, but feel free to comment if you have additional ideas or thoughts you'd like to mention.

Cheers,
Clint

**Comment by ellerbrock** [comment]
hi clint,

of course the examples where just meant as idea to use ci for further attacks (and some travis examples). i guess very less attackers would run linting or deadlink scans in an attack mode :D 
cheers maik

**Comment by clintgibler** [comment]
Ah yes, using CI for further attacks could be interesting, thanks!
